spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yourdbname?useSSL=false
    username: yourusername
    password: yourpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
